name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        # Using main as release please is often bumped more frequently than the action
        uses: googleapis/release-please-action@main
        with:
          config-file: release-please-config.json

      - name: Checkout Code
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: Setup Node
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Create Rebuffed Package
        if: ${{ steps.release.outputs['modules/rebuffed--release_created'] }}
        run: |
          npm i
          cd modules/rebuffed
          npm run build
          cd dist
          zip -r ${{ steps.release.outputs['modules/rebuffed--tag_name'] }}.zip .

      - name: Upload Rebuffed Package
        if: ${{ steps.release.outputs['modules/rebuffed--release_created'] }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release.outputs['modules/rebuffed--tag_name'] }}
          files: |
            modules/rebuffed/dist/${{ steps.release.outputs['modules/rebuffed--tag_name'] }}.zip
